# Generated by Django 5.1.6 on 2025-03-02 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date_joined_for_format',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login_for_format',
        ),
        migrations.AddField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
