# Generated by Django 5.1.5 on 2025-02-19 06:29

from django.db import migrations
from django.utils.text import slugify

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    SafetyStandard = apps.get_model('shop', 'SafetyStandard')
    
    # Create safety standards
    standards = [
        ('EN166', 'European standard for eye protection'),
        ('EN ISO 20345', 'Safety footwear standard'),
        ('EN397', 'Industrial safety helmets standard'),
        ('ANSI Z87.1', 'American standard for eye protection'),
        ('ANSI Z89.1', 'American standard for industrial head protection'),
    ]
    
    for name, description in standards:
        SafetyStandard.objects.create(name=name, description=description)
    
    # Create categories
    categories = [
        {
            'name': 'Safety Boots',
            'description': 'High-quality safety boots and shoes for industrial and construction use'
        },
        {
            'name': 'Hard Hats & Helmets',
            'description': 'Protective helmets and hard hats for construction and industrial applications'
        },
        {
            'name': 'Safety Goggles',
            'description': 'Eye protection equipment including safety glasses and goggles'
        },
        {
            'name': 'Road Safety',
            'description': 'Road signs, barriers, and traffic safety equipment'
        },
        {
            'name': 'High Visibility Clothing',
            'description': 'High visibility vests, jackets, and workwear'
        },
        {
            'name': 'Hand Protection',
            'description': 'Safety gloves and hand protection equipment'
        },
        {
            'name': 'Respiratory Protection',
            'description': 'Masks, respirators, and breathing apparatus'
        },
        {
            'name': 'Fall Protection',
            'description': 'Safety harnesses, lanyards, and fall arrest equipment'
        }
    ]
    
    for category_data in categories:
        Category.objects.create(
            name=category_data['name'],
            slug=slugify(category_data['name']),
            description=category_data['description']
        )

def remove_initial_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    SafetyStandard = apps.get_model('shop', 'SafetyStandard')
    Category.objects.all().delete()
    SafetyStandard.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_safetystandard_product_certifications_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
