# Generated by Django 5.1.5 on 2025-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (e.g., 20 for 20% off)', max_digits=5),
        ),
    ]
