# Generated by Django 5.1.5 on 2025-02-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_hubtelmomopayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_tarkwa', models.BooleanField(default=False)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance from Tarkwa in kilometers', max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverylocation'),
        ),
    ]
