# Generated by Django 5.1.5 on 2025-03-10 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_confirmation_order_delivery_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_confirmation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received_date',
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
